//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyRelations = new HashSet<CompanyRelation>();
            this.CompanyRelations1 = new HashSet<CompanyRelation>();
            this.CompanyUsers = new HashSet<CompanyUser>();
            this.Notifications = new HashSet<Notification>();
            this.Products = new HashSet<Product>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDescription { get; set; }
        public string CompanyLogo { get; set; }
        public bool CompanyIsActive { get; set; }
    
        public virtual ICollection<CompanyRelation> CompanyRelations { get; set; }
        public virtual ICollection<CompanyRelation> CompanyRelations1 { get; set; }
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
