//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRelation
    {
        public int CompanyRelationId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> RelatedAppUserId { get; set; }
        public Nullable<int> RelatedComanyId { get; set; }
        public bool CompanyRelationIsActive { get; set; }
        public int RelationshipTypeId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
    }
}
