//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EveEntities : DbContext
    {
        public EveEntities()
            : base("name=EveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyRelation> CompanyRelations { get; set; }
        public DbSet<CompanyUser> CompanyUsers { get; set; }
        public DbSet<Meta> Metas { get; set; }
        public DbSet<MetaOption> MetaOptions { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<NotificationUser> NotificationUsers { get; set; }
        public DbSet<OrderStatu> OrderStatus { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductMeta> ProductMetas { get; set; }
        public DbSet<RelationshipType> RelationshipTypes { get; set; }
        public DbSet<SaleOrder> SaleOrders { get; set; }
        public DbSet<SaleOrderDetail> SaleOrderDetails { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<ProductImage> ProductImages { get; set; }
        public DbSet<ProductRemark> ProductRemarks { get; set; }
    
        public virtual ObjectResult<usp_sel_ProductMetaInfo_Result> usp_sel_ProductMetaInfo(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_sel_ProductMetaInfo_Result>("usp_sel_ProductMetaInfo", pidParameter);
        }
    }
}
