//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meta
    {
        public Meta()
        {
            this.MetaOptions = new HashSet<MetaOption>();
        }
    
        public int MetaId { get; set; }
        public string MetaNameEs { get; set; }
        public string MetaNameEn { get; set; }
    
        public virtual ICollection<MetaOption> MetaOptions { get; set; }
    }
}
