//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaOption
    {
        public int MetaOptionId { get; set; }
        public int MetaId { get; set; }
        public string MetaOptionNameEs { get; set; }
        public string MetaOptionNameEn { get; set; }
        public string MetaOptionValue { get; set; }
    
        public virtual Meta Meta { get; set; }
    }
}
