//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationUsers = new HashSet<NotificationUser>();
        }
    
        public int NotificationId { get; set; }
        public int CompanyId { get; set; }
        public string NotificationMessage { get; set; }
        public System.DateTime NotificationDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<NotificationUser> NotificationUsers { get; set; }
    }
}
