//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationUser
    {
        public int NotificationUserId { get; set; }
        public int NotificationId { get; set; }
        public int AppUserId { get; set; }
        public Nullable<System.DateTime> NotificationUserSendDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
