//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public OrderStatu()
        {
            this.SaleOrders = new HashSet<SaleOrder>();
        }
    
        public int OrderStatusId { get; set; }
        public string OrderStatusNameEs { get; set; }
        public string OrderStatusNameEn { get; set; }
        public bool OrderStatusIsActive { get; set; }
    
        public virtual ICollection<SaleOrder> SaleOrders { get; set; }
    }
}
