//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRemark
    {
        public int ProductRemarkId { get; set; }
        public int ProductId { get; set; }
        public string ProductRemarkDescription { get; set; }
        public Nullable<System.DateTime> ProductRemarkStart { get; set; }
        public Nullable<System.DateTime> ProductRemarkEnd { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
