//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductMetas = new HashSet<ProductMeta>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductRemarks = new HashSet<ProductRemark>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ProductNameEs { get; set; }
        public string ProductNameEn { get; set; }
        public string ProductDescriptionEs { get; set; }
        public string ProductDescriptionEn { get; set; }
        public bool ProductIsActive { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal ProductRetailPrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<ProductMeta> ProductMetas { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<ProductRemark> ProductRemarks { get; set; }
    }
}
