//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetail
    {
        public int SaleOrderDetailId { get; set; }
        public int SaleOrderId { get; set; }
        public int ProductMetaId { get; set; }
        public decimal SaleOrderDetailPrice { get; set; }
        public int SaleOrderDetailAmmount { get; set; }
    
        public virtual ProductMeta ProductMeta { get; set; }
        public virtual SaleOrder SaleOrder { get; set; }
    }
}
