//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        public SaleOrder()
        {
            this.SaleOrderDetails = new HashSet<SaleOrderDetail>();
        }
    
        public int SaleOrderId { get; set; }
        public int AppUserId { get; set; }
        public int SaleOrderStatusId { get; set; }
        public string SaleOrderComments { get; set; }
        public System.DateTime SaleOrderCreationDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual ICollection<SaleOrderDetail> SaleOrderDetails { get; set; }
    }
}
